
program = {statement {NEWLINE}}

statement = 'INTEGER' command {':' command} 'NEWLINE'

command = 'REM'
        | 'LET' IDENTIFIER = expression
        | 'INPUT' STRING ';' IDENTIFIER
        | 'IF' expression 'THEN' (command | if_declare)
        | 'PRINT' STRING {(',' | ';') expression}
        | 'TEXT'
        | 'PR' '#' INTEGER
        | 'HOME'
        | 'GOSUB' INTEGER
        | 'RETURN'
        | 'GET' IDENTIFIER
        | 'GOTO' INTEGER
        | 'FOR' IDENTIFIER '=' expression 'TO' expression
        | 'NEXT' IDENTIFIER
        | 'END'

if_declare = IDENTIFIER '=' expression

expression = logic
logic = primary {('AND' | 'OR') primary}
primary = value
        | not_a_function
        | paren
        | binary

value = IDENTIFIER | INTEGER | STRING
not_a_function = ('CHR$' | 'STR$' | 'INT' | 'NOT') '(' expression ')'
binary = expression op expression
op = '+' | '-' | '/' | '*' | 'MOD'
paren = '(' expression ')'
